good = TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256

[frontend]
ciphers = TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256

[backend]
ciphers = TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
